data="PYTHON"
print("Base String is: ",data)
print("Forward")
print("-------")
print("1st Character :",data[0])
print("2nd Character :",data[1])
print("3rd Character :",data[2])
print("4th Character :",data[3])
print("5th Character :",data[4])
print("6th Character :",data[5])
print("Backward")
print("--------")
print("Last Character     :",data[-1])
print("2nd Last Character :",data[-2])
print("3rd Last Character :",data[-3])
print("4th Last Character :",data[-4])
print("5th Last Character :",data[-5])
print("6th Last Character :",data[-6])

